alias dbb='dart pub run build_runner build --delete-conflicting-outputs && flutter clean && flutter pub get'
alias db='dart pub run build_runner build --delete-conflicting-outputs'
alias fc='flutter clean'
alias fg='flutter pub get'
alias fcg='flutter clean && flutter pub get'